[tool.poetry]
name = "sqd-portal-client-evm"
version = "0.1.0"
description = "Thin SQD Network client for EVM data"
authors = ["Anton Bernatskiy <abernatskiy@toha.li>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
